version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: microservice-videos-admin:latest
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
